"""rename e_mail in users

Revision ID: 83d7d120863c
Revises: 5ed008c2e212
Create Date: 2021-06-16 00:37:46.686773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d7d120863c'
down_revision = '5ed008c2e212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'e_mail', new_column_name='email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email', new_column_name='e_mail')
    # ### end Alembic commands ###
